from gui_components.audio_panel import AudioPanel
from gui_components.epub_panel import EpubPanel
from gui_components.game_panel import GamePanel
from gui_components.log_panel import LogPanel
from gui_components.video_panel import VideoPanel